name: sam_apb_env
channels:
  - conda-forge
  - default
dependencies:
  - gdal=3.10.2
  - geopandas=1.0.1
  #- mamba=2.0.5
  - numpy=2.2.3
  # - py-opencv=4.11.0
  - pandas=2.2.3
  - python=3.12.9
  - shapely=2.0.7
  - segment-geospatial=0.12.4 
  - duckdb=1.2.0
  #- fire=0.7.0
  - matplotlib=3.10.0
  - pyproj=3.7.1
  - scipy=1.15.2
  - pyarrow=20.0.0
  - openpyxl=3.1.5
  - pip
  - pip:
    - git+https://github.com/google/python-fire.git