name: documentation github pages

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment_cpu.yaml
          activate-environment: sam_apb_env  # Replace with your env name if different
          auto-activate-base: false
          auto-update-conda: true

      - name: Install mkdocs
        run: conda run -n sam_apb_env pip install mkdocs mkdocstrings[python] mkdocs-material mkdocs-jupyter
      - name: Update markdown
        run: conda run -n sam_apb_env python docs/automate_index_md.py
      - name: Update yaml
        run: conda run -n sam_apb_env python docs/automate_yaml.py
      - name: Generate documentation
        run: conda run -n sam_apb_env mkdocs build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/ 

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4


