name: Publish to PyPI

on:
  push:
    branch:
     - main
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install build tools
        run: python -m pip install --upgrade build twine
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Verify version matches pyproject.toml
        run: |
          py_version=$(grep -E '^version\s*=' pyproject.toml | sed -E 's/version\s*=\s*"([^"]+)"/\1/')
          echo "pyproject.toml version: $py_version"
          echo "Git tag version: $VERSION"
          if [ "$py_version" != "$VERSION" ]; then
            echo "❌ Version mismatch: pyproject.toml = $py_version, tag = $VERSION"
            exit 1
          fi

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi
        run: python -m twine upload --verbose --non-interactive dist/*
